# -*- coding: utf-8 -*-
"""SQL Query Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGz12rlJRBmp1lRYjsWYRUMDLvWMyvk-
"""

!pip install -q gradio transformers torch reportlab requests

import gradio as gr
import re
import sqlite3
import datetime
import urllib.parse
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4

# ==========================
# DATABASE SCHEMA
# ==========================

schema = {
    "users": ["id", "name", "email", "signup_date", "age", "country", "status"],
    "orders": ["id", "user_id", "product_name", "amount", "order_date", "status"],
    "products": ["id", "name", "price", "category", "stock"],
    "transactions": ["id", "user_id", "amount", "date", "type"]
}

query_history = []

# ==========================
# SECURITY SYSTEM
# ==========================

dangerous_keywords = [
    "drop", "delete", "alter", "truncate",
    "insert", "update", "exec", "execute"
]

dangerous_patterns = [
    r";", r"--", r"/\*", r"\*/", r"xp_", r"sp_"
]

def is_safe(user_input):
    text = user_input.lower()
    for word in dangerous_keywords:
        if word in text:
            return False
    for pattern in dangerous_patterns:
        if re.search(pattern, text):
            return False
    return True

# ==========================
# TABLE DETECTION
# ==========================

def get_table_name(text):
    text = text.lower()
    if any(k in text for k in ["user", "customer", "account", "profile"]):
        return "users"
    if any(k in text for k in ["order", "purchase", "buy"]):
        return "orders"
    if any(k in text for k in ["product", "item", "goods"]):
        return "products"
    if any(k in text for k in ["transaction", "payment", "transfer"]):
        return "transactions"
    return None

# ==========================
# CONDITION EXTRACTION
# ==========================

def extract_conditions(text, table):
    conditions = []

    # Amount condition
    amount_match = re.search(r"(greater than|more than|above)\s+(\d+)", text)
    if amount_match:
        conditions.append(f"amount > {amount_match.group(2)}")

    # Last week
    if "last week" in text:
        if table == "transactions":
            conditions.append("DATE(date) >= DATE('now','-7 days')")
        else:
            conditions.append("DATE(signup_date) >= DATE('now','-7 days')")

    # Last month
    if "last month" in text:
        if table == "users":
            conditions.append("DATE(signup_date) >= DATE('now','-1 month')")

    return " AND ".join(conditions)

# ==========================
# SQL GENERATION
# ==========================

def generate_sql(user_input):
    if not is_safe(user_input):
        return "❌ Dangerous SQL detected. Query blocked."

    table = get_table_name(user_input)
    if not table:
        return "❌ Could not detect table."

    conditions = extract_conditions(user_input.lower(), table)

    query = f"SELECT * FROM {table}"
    if conditions:
        query += f" WHERE {conditions}"

    query += " LIMIT 10"

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    query_history.append((user_input, query, timestamp))

    return query

# ==========================
# PDF EXPORT
# ==========================

def export_pdf():
    filename = f"SQL_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    elements.append(Paragraph("SQL Query Report", styles["Heading1"]))
    elements.append(Spacer(1, 12))

    for i, (req, sql, time) in enumerate(query_history):
        elements.append(Paragraph(f"{i+1}. Request: {req}", styles["Normal"]))
        elements.append(Paragraph(f"SQL: {sql}", styles["Code"]))
        elements.append(Paragraph(f"Generated at: {time}", styles["Normal"]))
        elements.append(Spacer(1, 12))

    doc.build(elements)
    return filename

# ==========================
# TEXT EXPORT
# ==========================

def export_text():
    filename = f"SQL_Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    with open(filename, "w") as f:
        for req, sql, time in query_history:
            f.write(f"Request: {req}\nSQL: {sql}\nTime: {time}\n\n")
    return filename

# ==========================
# SOCIAL SHARE
# ==========================

def whatsapp_share():
    if not query_history:
        return ""
    message = "\n".join([q[1] for q in query_history[-5:]])
    encoded = urllib.parse.quote(message)
    return f"https://wa.me/?text={encoded}"

def facebook_share():
    if not query_history:
        return ""
    message = "\n".join([q[1] for q in query_history[-3:]])
    encoded = urllib.parse.quote(message)
    return f"https://www.facebook.com/sharer/sharer.php?u={encoded}"

# ==========================
# GRADIO INTERFACE
# ==========================

with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 🚀 SQL Query Generator")
    chatbot = gr.Chatbot()

    user_input = gr.Textbox(placeholder="Enter your request in natural language...")
    generate_btn = gr.Button("Generate SQL")
    clear_btn = gr.Button("Clear History")

    pdf_btn = gr.Button("Export PDF")
    txt_btn = gr.Button("Export Text")
    wa_btn = gr.Button("Share WhatsApp")
    fb_btn = gr.Button("Share Facebook")

    def chat(user_message, history):
        sql = generate_sql(user_message)
        history.append((user_message, sql))
        return history

    generate_btn.click(chat, [user_input, chatbot], chatbot)
    clear_btn.click(lambda: [], None, chatbot)

    pdf_btn.click(export_pdf, None, gr.File())
    txt_btn.click(export_text, None, gr.File())
    wa_btn.click(whatsapp_share, None, gr.Textbox())
    fb_btn.click(facebook_share, None, gr.Textbox())

demo.launch(share=True)